# Generated by Django 5.2.10 on 2026-02-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='score',
            field=models.IntegerField(blank=True, help_text='AI-evaluated score 0–100', null=True),
        ),
    ]
