# Generated by Django 5.2.10 on 2026-02-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0002_answermodel_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='topic',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='category',
            field=models.CharField(choices=[('Investment Banking', 'Investment Banking'), ('Consulting', 'Consulting')], default='Investment Banking', max_length=30),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='subcategory',
            field=models.CharField(choices=[('Behavioral', 'Behavioral'), ('Financial', 'Financial'), ('Case', 'Case')], default='Behavioral', max_length=20),
        ),
    ]
