# Generated by Django 5.2.10 on 2026-02-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0003_remove_questionmodel_topic_questionmodel_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answermodel',
            name='score',
        ),
    ]
